# Generated by Django 4.2.30 on 2026-08-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenderapplication',
            name='proposal_document',
            field=models.FileField(blank=True, null=True, upload_to='tender_applications/'),
        ),
    ]
