# Generated by Django 4.1.13 on 2026-02-27 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='description',
        ),
        migrations.RemoveField(
            model_name='team',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='team',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='team',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='team',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='team',
            name='whatsapp',
        ),
    ]
