# Generated by Django 4.2.13 on 2025-05-20 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("member", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_budget",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "spent_budget",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
                ),
                ("budget_date", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budgets",
                        to="member.project",
                    ),
                ),
            ],
        ),
    ]
