# Generated by Django 4.1.13 on 2026-04-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenderapplication',
            name='financial_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tenderapplication',
            name='technical_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tenderapplication',
            name='total_score',
            field=models.FloatField(default=0),
        ),
    ]
