# Generated by Django 4.1.13 on 2026-02-15 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_project_contact_email_project_progress_update_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='testimonial_text',
        ),
    ]
