# Generated by Django 4.1.13 on 2026-04-28 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_tenderapplication_financial_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='pipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
