# Generated by Django 4.2.30 on 2026-08-20 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_tenderapplication_proposal_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project_division',
            options={'ordering': ['name', '-created_at'], 'verbose_name': 'Project Division', 'verbose_name_plural': 'Project Divisions'},
        ),
        migrations.AddField(
            model_name='project',
            name='project_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='member.project_division'),
        ),
        migrations.AddField(
            model_name='project_division',
            name='allocated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='project_division',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='project_division',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='project_division',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='project_division',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project_division',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project_division',
            name='head_of_division',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='project_division',
            name='head_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_divisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project_division',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='divisions/'),
        ),
        migrations.AddField(
            model_name='project_division',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project_division',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='project_division',
            name='office_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project_division',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_division',
            name='project_name',
            field=models.ManyToManyField(blank=True, related_name='project_list', to='member.project'),
        ),
        migrations.AlterField(
            model_name='project_division',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisions', to='member.project_type'),
        ),
    ]
