# Generated by Django 4.2.30 on 2026-08-20 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_project_division_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='governmentrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='governmentrequest',
            name='official_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='governmentrequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Low Priority'), ('medium', 'Medium Priority'), ('high', 'High Priority'), ('urgent', 'Urgent Action Needed')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='governmentrequest',
            name='reference_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='governmentrequest',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='governmentrequest',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='governmentrequest',
            name='citizen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='governmentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('in_progress', 'Under Investigation'), ('responded', 'Official Response Provided'), ('resolved', 'Resolved'), ('rejected', 'Rejected / Dismissed'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
    ]
