# Generated by Django 5.0.2 on 2024-03-14 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_user_is_enduser_alter_user_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_division',
            name='Project_Division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.project'),
        ),
    ]
