# Generated by Django 4.1.13 on 2026-02-15 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_remove_testimonial_testimonial_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
    ]
