# Generated by Django 4.1.13 on 2026-03-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_team_description_team_facebook_team_instagram_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_division',
            name='name',
        ),
        migrations.AddField(
            model_name='project_division',
            name='project_name',
            field=models.ManyToManyField(blank=True, related_name='divisions', to='member.project'),
        ),
    ]
