# Generated by Django 4.2.7 on 2025-05-20 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_remove_testimonial_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='member.project'),
        ),
    ]
