# Generated by Django 4.1.13 on 2026-04-28 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_tender_pipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='pipo',
        ),
        migrations.AddField(
            model_name='tender',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tenderapplication',
            name='tender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='member.tender'),
        ),
    ]
