# Generated by Django 5.0.2 on 2024-03-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_project_division_project_division'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project_division',
            old_name='Project_Division',
            new_name='status',
        ),
    ]
