# Generated by Django 4.1.13 on 2026-03-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_remove_project_division_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='division',
        ),
        migrations.AlterField(
            model_name='project_division',
            name='project_name',
            field=models.ManyToManyField(related_name='project_list', to='member.project'),
        ),
    ]
