# Generated by Django 4.2.30 on 2026-08-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_governmentrequest_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('ongoing', 'Ongoing'), ('upcoming', 'Upcoming'), ('completed', 'Completed'), ('delayed', 'Delayed'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('stalled', 'Stalled')], default='draft', max_length=20, null=True),
        ),
    ]
