# Generated by Django 4.2.7 on 2025-05-20 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_remove_testimonial_description_testimonial_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
