# Generated by Django 4.1.13 on 2026-03-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_remove_project_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
        migrations.AddField(
            model_name='project_type',
            name='project_Types',
            field=models.ManyToManyField(blank=True, null=True, related_name='project_types', to='member.project'),
        ),
    ]
