# Generated by Django 4.1.13 on 2026-02-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_testimonial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
            ],
        ),
    ]
