# Generated by Django 5.0.2 on 2024-03-14 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_rename_project_division_project_division_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_division',
            name='project_type',
        ),
        migrations.AddField(
            model_name='project_division',
            name='project_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.project_type'),
        ),
    ]
