# Generated by Django 4.1.13 on 2026-02-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
