# Generated by Django 4.1.13 on 2026-03-02 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_remove_project_project_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_type',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project_type',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_types_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project_type',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project_type',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project_type',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_type',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='project_type',
            name='project_Types',
            field=models.ManyToManyField(blank=True, related_name='project_types', to='member.project'),
        ),
    ]
