# Generated by Django 4.2.30 on 2026-09-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_contractor_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenevidence',
            name='category',
            field=models.CharField(choices=[('infrastructure', 'Infrastructure'), ('water', 'Water & Sanitation'), ('health', 'Health'), ('education', 'Education'), ('security', 'Security'), ('environment', 'Environment'), ('corruption', 'Corruption'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='citizenevidence',
            name='coordinates',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='citizenevidence',
            name='evidence_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio'), ('other', 'Other')], default='photo', max_length=20),
        ),
        migrations.AddField(
            model_name='citizenevidence',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citizenevidence',
            name='observed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citizenevidence',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='moderate', max_length=20),
        ),
        migrations.DeleteModel(
            name='Contractor_projects',
        ),
    ]
