# Generated by Django 4.1.13 on 2026-03-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_project_type_created_at_project_type_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='progress_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
