# Generated by Django 5.0.2 on 2024-03-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_rename_status_project_division_project_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='avatar.png', null=True, upload_to='images'),
        ),
    ]
