# Generated by Django 4.2.7 on 2025-05-20 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='email',
        ),
    ]
