# Generated by Django 5.0.2 on 2024-03-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='avatar.png', null=True, upload_to='profile'),
        ),
    ]
