# Generated by Django 4.2.7 on 2025-05-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_remove_testimonial_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
