# Generated by Django 4.1.13 on 2026-03-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_alter_project_progress_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
