# Generated by Django 4.2.7 on 2025-05-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_remove_testimonial_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('upcoming', 'Upcoming'), ('completed', 'Completed'), ('stalled', 'Stalled'), ('Delayed', 'Delayed'), ('overview', 'overview')], max_length=10),
        ),
    ]
