# Generated by Django 4.2.13 on 2024-08-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdf',
            options={'verbose_name': 'PDF', 'verbose_name_plural': 'PDFs'},
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='project_Budget',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='project_description',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='project_images',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='project_location',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='project_status',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='start_date',
        ),
        migrations.AddField(
            model_name='pdf',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='implementing_agency',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='project_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pdf',
            name='Project_status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
