# Generated by Django 4.2.30 on 2026-09-05 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_restore_stagereport_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatmessage',
            name='feedback',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('bad', 'Bad')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aichatmessage',
            name='model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aichatsession',
            name='title',
            field=models.CharField(default='New Conversation', max_length=255),
        ),
        migrations.AlterField(
            model_name='aiissueassessment',
            name='category',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aiissueassessment',
            name='model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aiissueassessment',
            name='provider',
            field=models.CharField(default='heuristic', max_length=255),
        ),
        migrations.AlterField(
            model_name='aiissueassessment',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending Staff Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='aiissueassessment',
            name='urgency',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aireportgeneration',
            name='model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aireportgeneration',
            name='report_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aireportgeneration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=255),
        ),
        migrations.CreateModel(
            name='AIFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('category', models.CharField(choices=[('financial_progress', 'Financial/Physical Progress Mismatch'), ('progress_jump', 'Unusual Progress Change'), ('progress_inactivity', 'Project Inactivity'), ('cost_anomaly', 'Cost Anomaly vs Peers'), ('peer_outlier', 'Statistical Peer Outlier'), ('duplicate', 'Possible Duplicate Project'), ('relationship', 'Relationship Anomaly'), ('contractor', 'Contractor Behaviour'), ('procurement', 'Procurement Anomaly'), ('reporting', 'Reporting Inconsistency'), ('complaints', 'Citizen Complaint Signal'), ('delay_prediction', 'Delay Prediction'), ('cost_overrun', 'Cost Overrun Prediction'), ('data_quality', 'Data Quality')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('finding', models.TextField()),
                ('reason', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('priority_score', models.FloatField(default=0)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending Human Review'), ('investigating', 'Under Investigation'), ('confirmed', 'Confirmed Anomaly'), ('false_positive', 'False Positive')], default='pending', max_length=255)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_findings', to='member.contractor')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_findings', to='member.project')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_findings', to=settings.AUTH_USER_MODEL)),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_findings', to='member.tender')),
            ],
            options={
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIEngineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects_scanned', models.IntegerField(default=0)),
                ('findings_created', models.IntegerField(default=0)),
                ('findings_active', models.IntegerField(default=0)),
                ('model', models.CharField(default='govtracker-engine-v1', max_length=100)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]

