# Generated by Django 4.2.30 on 2026-09-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_alter_aichatmessage_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aichatmessage',
            name='feedback',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('bad', 'Bad')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='aichatmessage',
            name='model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aichatsession',
            name='title',
            field=models.CharField(default='New Conversation', max_length=255),
        ),
        migrations.AlterField(
            model_name='aifinding',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Human Review'), ('investigating', 'Under Investigation'), ('confirmed', 'Confirmed Anomaly'), ('false_positive', 'False Positive')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='aiissueassessment',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
