# Generated by Django 4.1.13 on 2026-02-22 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='participants',
            field=models.ManyToManyField(blank=True, null=True, related_name='message_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
