# Generated by Django 4.1.13 on 2026-03-08 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_alter_project_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tender',
            name='created_by',
        ),
    ]
