# Generated by Django 4.2.30 on 2026-09-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_alter_aichatmessage_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiissueassessment',
            name='model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aiissueassessment',
            name='provider',
            field=models.CharField(default='heuristic', max_length=255),
        ),
        migrations.AlterField(
            model_name='aiissueassessment',
            name='review_status',
            field=models.CharField(choices=[('pending', 'Pending Staff Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='aiissueassessment',
            name='urgency',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aireportgeneration',
            name='model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aireportgeneration',
            name='report_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aireportgeneration',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=255),
        ),
    ]
