# Generated by Django 4.1.13 on 2026-03-08 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_remove_tender_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='created_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tenders', to=settings.AUTH_USER_MODEL),
        ),
    ]
