# Generated by Django 3.2.16 on 2025-03-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_auto_20250306_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='status',
            new_name='project_status',
        ),
    ]
