# Generated by Django 4.2.21 on 2025-06-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_project_contractor_project_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='progress_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
