# Generated by Django 4.1.13 on 2026-02-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_remove_project_participants_participation'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
