# Generated by Django 4.1.13 on 2026-03-09 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_tender_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderapplication',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='tenderapplication',
            name='financial_proposal',
        ),
        migrations.RemoveField(
            model_name='tenderapplication',
            name='technical_proposal',
        ),
        migrations.AddField(
            model_name='tenderapplication',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenderapplication',
            name='company_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenderapplication',
            name='company_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tenderapplication',
            name='company_phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tenderapplication',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to='tender_coverLetter'),
        ),
        migrations.AddField(
            model_name='tenderapplication',
            name='proposal_document',
            field=models.FileField(null=True, upload_to='tender_applications/'),
        ),
        migrations.AlterField(
            model_name='tenderapplication',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='tenderapplication',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('awarded', 'Awarded')], default='submitted', max_length=20),
        ),
    ]
