# Generated by Django 4.1.13 on 2026-03-14 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_remove_tenderapplication_contractor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='recipient',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('project', 'New Project'), ('participation', 'Project Participation'), ('comment', 'New Comment'), ('update', 'Project Update')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
