# Generated by Django 4.2.30 on 2026-09-18 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_community_discussion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussionreply',
            name='email',
        ),
        migrations.RemoveField(
            model_name='discussionreply',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='discussionreply',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='discussionreply',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='discussionreply',
            name='project',
        ),
        migrations.RemoveField(
            model_name='discussionreply',
            name='rating',
        ),
        migrations.AddField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='feedback',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='member.project'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True),
        ),
        migrations.AlterField(
            model_name='discussionreply',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussion_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='discussionreply',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='discussionreply',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='member.discussiontopic'),
        ),
        migrations.AlterField(
            model_name='discussiontopic',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discussiontopic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
