# Generated by Django 4.1.13 on 2026-02-23 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_participation_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messages',
            name='participants',
        ),
    ]
