# Generated by Django 4.2.21 on 2025-06-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_project_contact_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='contractor',
            new_name='project_contractor',
        ),
        migrations.RemoveField(
            model_name='project',
            name='progress_percentage',
        ),
        migrations.AddField(
            model_name='project',
            name='progress_update',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
