# Generated by Django 3.2.16 on 2025-03-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_alter_project_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='project',
        ),
    ]
