# Generated by Django 4.2.30 on 2026-09-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_remove_discussionreply_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstage',
            name='completed_on',
            field=models.DateField(
                blank=True,
                help_text='Auto-set when the stage is marked completed.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='projectstage',
            name='status',
            field=models.CharField(
                choices=[
                    ('not_started', 'Not Started'),
                    ('in_progress', 'In Progress'),
                    ('completed', 'Completed'),
                    ('delayed', 'Delayed'),
                    ('on_hold', 'On Hold'),
                ],
                db_index=True,
                default='not_started',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='stage_name',
            field=models.CharField(
                choices=[
                    ('planning', 'Planning & Design'),
                    ('procurement', 'Procurement & Tendering'),
                    ('site_clearance', 'Site Clearance & Land Preparation'),
                    ('foundation', 'Foundation & Substructure'),
                    ('superstructure', 'Superstructure / Main Works'),
                    ('finishing', 'Finishing & Fittings'),
                    ('inspection', 'Inspection & Quality Assurance'),
                    ('construction', 'Construction (General)'),
                    ('completion', 'Completion'),
                    ('monitoring', 'Monitoring & Evaluation'),
                    ('handover', 'Handover'),
                    ('others', 'Others'),
                ],
                max_length=30,
            ),
        ),
    ]
