# Generated by Django 3.2.16 on 2025-03-06 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_remove_media_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='member.project'),
        ),
    ]
