# Generated by Django 4.1.13 on 2026-03-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='amount_spent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_Budgeting',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
