# Generated by Django 4.1.13 on 2026-02-23 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_remove_messages_participants'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='participation',
            name='role',
        ),
    ]
