# Generated by Django 4.2.30 on 2026-09-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_projectstage_completed_on_projectstage_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('project', 'New Project'), ('participation', 'Project Participation'), ('comment', 'New Comment'), ('update', 'Project Update'), ('tender', 'Tender Alert'), ('issue', 'Issue Reported'), ('deadline', 'Project Deadline Alert'), ('ai', 'AI Recommendation'), ('system', 'System Alert')], max_length=20, null=True),
        ),
    ]
