# Generated by Django 3.2.16 on 2025-03-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_media_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='project',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('official', 'Government Official'), ('contractor', 'Contractor'), ('engineer', 'Engineer'), ('architect', 'Architect'), ('surveyor', 'Surveyor'), ('planner', 'Urban Planner'), ('developer', 'Software Developer'), ('analyst', 'Data Analyst'), ('manager', 'Project Manager'), ('others', 'others'), ('staff', 'Staff'), ('guest', 'Guest'), ('developer', 'Developer'), ('manager', 'Manager')], default='citizen', max_length=20),
        ),
    ]
