# Generated by Django 4.1.13 on 2026-04-25 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_citizensubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('progress_percentage', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='stage_reports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.contractor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.project')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.projectstage')),
            ],
        ),
        migrations.CreateModel(
            name='ContractorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_score', models.IntegerField(default=0)),
                ('speed_score', models.IntegerField(default=0)),
                ('compliance_score', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.contractor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.project')),
            ],
        ),
    ]
