# Generated by Django 3.2.16 on 2025-03-11 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0020_auto_20250307_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='Project_status',
            new_name='project_status',
        ),
        migrations.RemoveField(
            model_name='tender',
            name='file',
        ),
        migrations.AddField(
            model_name='media',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='member.project'),
        ),
        migrations.AlterField(
            model_name='projectlocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='projectlocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='closing_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='opening_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenders', to='member.project'),
        ),
        migrations.AlterField(
            model_name='tender',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
