# Generated by Django 4.1.13 on 2026-04-25 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0020_citizenevidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexpense',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='member.budget'),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projectrisk',
            name='risk_description',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='ProjectBudget',
        ),
    ]
