# Generated by Django 3.2.16 on 2025-03-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0021_auto_20250311_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlocation',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='projectlocation',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True),
        ),
    ]
