# Generated by Django 3.2.16 on 2025-03-12 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0023_auto_20250311_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('citizen', 'Citizen'), ('official', 'Government Official'), ('contractor', 'Contractor'), ('engineer', 'Engineer'), ('architect', 'Architect'), ('surveyor', 'Surveyor'), ('planner', 'Urban Planner'), ('developer', 'Software Developer'), ('analyst', 'Data Analyst'), ('manager', 'Project Manager'), ('others', 'others'), ('staff', 'Staff'), ('guest', 'Guest')], default='citizen', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(choices=[('planning', 'Planning'), ('procurement', 'Procurement'), ('construction', 'Construction'), ('completion', 'Completion')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='member.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_reported', models.DateTimeField(auto_now_add=True)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='member.project')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='member.projectstage')),
            ],
        ),
        migrations.AddField(
            model_name='milestone',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='member.projectstage'),
        ),
    ]
