# Generated by Django 3.2.16 on 2025-03-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0024_auto_20250312_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='completion_date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='stage_name',
            field=models.CharField(choices=[('planning', 'Planning'), ('procurement', 'Procurement'), ('construction', 'Construction'), ('completion', 'Completion'), ('monitoring', 'Monitoring'), ('evaluation', 'Evaluation'), ('others', 'Others')], max_length=20),
        ),
    ]
