# Generated by Django 3.2.16 on 2025-03-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0025_auto_20250312_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programfunding',
            old_name='program',
            new_name='project',
        ),
        migrations.AlterField(
            model_name='project_division',
            name='project_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='divisions', to='member.project_type'),
        ),
        migrations.AlterField(
            model_name='projectstage',
            name='progress_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
