# Generated by Django 3.2.16 on 2025-03-12 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0026_auto_20250312_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_Budgeting',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
